// Real kit renders (user-generated, see frontend-v2/public/kits/) covering
// all 72 clubs across EFL Fantasy's three divisions (Championship, League
// One, League Two). Kit.tsx falls back to the generic colour-based SVG
// jersey for any team name not listed here (every other game's real clubs),
// so adding more images later is just dropping a new PNG in public/kits/
// and adding one line below.
export const KIT_IMAGES: Record<string, string> = {
  // Championship
  "Wolverhampton Wanderers": "/kits/wolverhampton-wanderers.png",
  "Blackburn Rovers": "/kits/blackburn-rovers.png",
  "Bolton Wanderers": "/kits/bolton-wanderers.png",
  "Preston North End": "/kits/preston-north-end.png",
  "Bristol City": "/kits/bristol-city.png",
  Millwall: "/kits/millwall.png",
  "Charlton Athletic": "/kits/charlton-athletic.png",
  "Derby County": "/kits/derby-county.png",
  Middlesbrough: "/kits/middlesbrough.png",
  "Lincoln City": "/kits/lincoln-city.png",
  "Norwich City": "/kits/norwich-city.png",
  "West Bromwich Albion": "/kits/west-bromwich-albion.png",
  Portsmouth: "/kits/portsmouth.png",
  "Queens Park Rangers": "/kits/queens-park-rangers.png",
  "Stoke City": "/kits/stoke-city.png",
  "Swansea City": "/kits/swansea-city.png",
  "Sheffield United": "/kits/sheffield-united.png",
  "Birmingham City": "/kits/birmingham-city.png",
  Watford: "/kits/watford.png",
  Southampton: "/kits/southampton.png",
  Burnley: "/kits/burnley.png",
  "West Ham United": "/kits/west-ham-united.png",
  "Cardiff City": "/kits/cardiff-city.png",
  Wrexham: "/kits/wrexham.png",

  // League One
  "Notts County": "/kits/notts-county.png",
  "Leicester City": "/kits/leicester-city.png",
  "Oxford United": "/kits/oxford-united.png",
  "MK Dons": "/kits/mk-dons.png",
  Reading: "/kits/reading.png",
  "Luton Town": "/kits/luton-town.png",
  Barnsley: "/kits/barnsley.png",
  Bromley: "/kits/bromley.png",
  Blackpool: "/kits/blackpool.png",
  "Wycombe Wanderers": "/kits/wycombe-wanderers.png",
  "Bradford City": "/kits/bradford-city.png",
  "Peterborough United": "/kits/peterborough-united.png",
  "Burton Albion": "/kits/burton-albion.png",
  Stevenage: "/kits/stevenage.png",
  "Cambridge United": "/kits/cambridge-united.png",
  "Wigan Athletic": "/kits/wigan-athletic.png",
  "Huddersfield Town": "/kits/huddersfield-town.png",
  "AFC Wimbledon": "/kits/afc-wimbledon.png",
  "Leyton Orient": "/kits/leyton-orient.png",
  "Sheffield Wednesday": "/kits/sheffield-wednesday.png",
  "Mansfield Town": "/kits/mansfield-town.png",
  "Doncaster Rovers": "/kits/doncaster-rovers.png",
  "Plymouth Argyle": "/kits/plymouth-argyle.png",
  "Stockport County": "/kits/stockport-county.png",

  // League Two
  "Newport County": "/kits/newport-county.png",
  Rochdale: "/kits/rochdale.png",
  "Oldham Athletic": "/kits/oldham-athletic.png",
  "Port Vale": "/kits/port-vale.png",
  "Accrington Stanley": "/kits/accrington-stanley.png",
  "Colchester United": "/kits/colchester-united.png",
  Barnet: "/kits/barnet.png",
  "Salford City": "/kits/salford-city.png",
  "Cheltenham Town": "/kits/cheltenham-town.png",
  "Rotherham United": "/kits/rotherham-united.png",
  Chesterfield: "/kits/chesterfield.png",
  "Fleetwood Town": "/kits/fleetwood-town.png",
  "Crawley Town": "/kits/crawley-town.png",
  "Crewe Alexandra": "/kits/crewe-alexandra.png",
  Gillingham: "/kits/gillingham.png",
  Walsall: "/kits/walsall.png",
  "Grimsby Town": "/kits/grimsby-town.png",
  "Exeter City": "/kits/exeter-city.png",
  "Northampton Town": "/kits/northampton-town.png",
  "Swindon Town": "/kits/swindon-town.png",
  "Tranmere Rovers": "/kits/tranmere-rovers.png",
  "Shrewsbury Town": "/kits/shrewsbury-town.png",
  "York City": "/kits/york-city.png",
  "Bristol Rovers": "/kits/bristol-rovers.png",
};

export function getKitImage(teamName: string): string | null {
  return KIT_IMAGES[teamName] ?? null;
}
