"""
merge_reclassified_player_duplicates.py
-----------------------------------------
One-off, logged, reversible data fix for a root cause confirmed while
investigating scripts/audit_player_role.py's "duplicate player" finding.
Corrected diagnosis: these 4 aren't Dream Team clones - they're FanTeam
duplicates caused by a real bug in import_players() (see the
"position bucket" fallback added to import_fanteam_live.py in the same
change as this script): FanTeam reclassified each player's position
(Ethan Ampadu DEF->MID, Evann Guessand FWD->MID, Lamare Bogarde DEF->MID,
Mats Wieffer MID->DEF), the old position-bucketed name search could no
longer find their existing row, and a brand new player + game_player row
got created instead - leaving the ORIGINAL row (with real 2025/26
history) inactive and the NEW row (zero history) active.

For each pair: reactivates the ORIGINAL game_player row (which holds the
real historical stats), refreshes it with the NEW row's more current
external_id/position_code/price/team_id (and players.position/team_id),
then deactivates the NEW (phantom) row. The phantom `players` row is left
in place, orphaned, not deleted - reversible, no other table touched.
Confirmed via direct query that no squad_players/watchlist_entries rows
reference any of the 4 phantom game_player_ids (real users never had
these in a squad) - the only references are historical
projections/player_gameweek_predictions/fanteam_player_status rows
generated by past pipeline runs, which are left as harmless orphaned
history rather than migrated (the reactivated original row already has
its own complete, correct history).

RUN:
    python3 scripts/merge_reclassified_player_duplicates.py            # dry run, logs only
    python3 scripts/merge_reclassified_player_duplicates.py --apply    # logs, then writes
"""
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import psycopg2
import psycopg2.extras

ROOT = Path(__file__).resolve().parent.parent

# (original_player_id, phantom_player_id) - both already confirmed by
# audit_player_role.py + a manual DB check to be the same real person,
# reclassified by FanTeam's live feed.
PAIRS = [
    (37, 765),   # Ethan Ampadu
    (92, 729),   # Evann Guessand
    (442, 724),  # Lamare Bogarde
    (50, 737),   # Mats Wieffer
]


def load_env():
    env_path = ROOT / ".env"
    if not env_path.exists():
        return
    for line in env_path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip())


def main():
    apply = "--apply" in sys.argv[1:]
    load_env()
    conn = psycopg2.connect(os.environ["DATABASE_URL"])
    cur = conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor)

    cur.execute("select id from fantasy_games where slug = 'fanteam'")
    fanteam_id = cur.fetchone()["id"]

    log = []
    for original_id, phantom_id in PAIRS:
        cur.execute(
            """
            select p.id as player_id, p.full_name, p.position, p.team_id,
                   gp.id as game_player_id, gp.external_id, gp.position_code, gp.price, gp.is_active
            from players p join game_players gp on gp.player_id = p.id and gp.game_id = %s
            where p.id = any(%s)
            order by p.id
            """,
            (fanteam_id, [original_id, phantom_id]),
        )
        rows = {r["player_id"]: r for r in cur.fetchall()}
        original, phantom = rows[original_id], rows[phantom_id]

        # Sanity check: refuse to touch anything unless the shape still
        # matches what we verified (original inactive, phantom active) -
        # a re-run after something else changed should no-op loudly, not
        # blindly reapply.
        if original["is_active"] or not phantom["is_active"]:
            print(f"[SKIP] {original['full_name']}: shape no longer matches (original.is_active={original['is_active']}, phantom.is_active={phantom['is_active']}) - already fixed or changed since this script was written.")
            continue

        entry = {
            "player_name": original["full_name"],
            "original": dict(original),
            "phantom": dict(phantom),
            "action": {
                "reactivate_game_player_id": original["game_player_id"],
                "new_external_id": phantom["external_id"],
                "new_position_code": phantom["position_code"],
                "new_price": str(phantom["price"]),
                "new_team_id": phantom["team_id"],
                "new_position": phantom["position"],
                "deactivate_game_player_id": phantom["game_player_id"],
            },
        }
        log.append(entry)
        print(f"--- {original['full_name']} ---")
        print(f"  original: player_id={original_id} game_player_id={original['game_player_id']} position={original['position']} team_id={original['team_id']} is_active={original['is_active']}")
        print(f"  phantom:  player_id={phantom_id} game_player_id={phantom['game_player_id']} position={phantom['position']} team_id={phantom['team_id']} is_active={phantom['is_active']}")
        print(f"  -> reactivate game_player_id={original['game_player_id']}, sync to position={phantom['position']}, team_id={phantom['team_id']}, price={phantom['price']}, external_id={phantom['external_id']}")
        print(f"  -> deactivate phantom game_player_id={phantom['game_player_id']}")

    log_path = ROOT / f"merge_reclassified_player_duplicates_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}.json"
    log_path.write_text(json.dumps(log, indent=2, default=str))
    print(f"\nLogged {len(log)} planned merges to {log_path}")

    if not apply:
        print("\nDry run only (no --apply flag) - no rows changed.")
        cur.close()
        conn.close()
        return

    for entry in log:
        a = entry["action"]
        # Deactivate the phantom AND clear its external_id FIRST - the
        # original row is about to take over that same external_id, and
        # (game_id, external_id) is uniquely constrained, so both rows
        # would momentarily collide if this ran in the other order.
        # "merged-<phantom_game_player_id>" keeps the value unique and
        # marks in the data itself why this row is now dead.
        cur.execute(
            "update game_players set is_active = false, external_id = %s, updated_at = now() where id = %s",
            (f"merged-{a['deactivate_game_player_id']}", a["deactivate_game_player_id"]),
        )
        cur.execute(
            "update players set position = %s, team_id = %s where id = %s",
            (a["new_position"], a["new_team_id"], entry["original"]["player_id"]),
        )
        cur.execute(
            """
            update game_players
            set is_active = true, external_id = %s, position_code = %s, price = %s, updated_at = now()
            where id = %s
            """,
            (a["new_external_id"], a["new_position_code"], a["new_price"], a["reactivate_game_player_id"]),
        )
    conn.commit()
    print(f"\nApplied: {len(log)} players merged back to their original identity.")
    cur.close()
    conn.close()


if __name__ == "__main__":
    main()
