-- Mary Performance Lab, Part 1 - real algorithm versioning.
--
-- get_or_create_algorithm_version() in scripts/compute_projections.py has
-- always upserted on version_label, so a weights change silently
-- overwrote the same row rather than creating history - fine while
-- pre-season tuning was "a bug fix, not a new tunable version" (its own
-- prior docstring), but the whole point of the Performance Lab is
-- comparing prediction accuracy ACROSS algorithm changes, which needs
-- every distinct weights set to survive as its own row.
--
-- `family` groups revisions of "the same algorithm" (e.g. "v2-decomposed"),
-- `revision` increments only when the weights for that family actually
-- change. version_label becomes "family.revision" (e.g.
-- "v2-decomposed.3"), generated by the Python code, not a DB generated
-- column - this codebase doesn't use those anywhere else.
--
-- Backfill: the single existing row per family (there's currently one
-- row per label, e.g. "v1" and "v2-decomposed") becomes revision 1 of a
-- family matching its current label.

alter table algorithm_versions add column family text;
alter table algorithm_versions add column revision integer;

update algorithm_versions set family = version_label, revision = 1 where family is null;

alter table algorithm_versions alter column family set not null;
alter table algorithm_versions alter column revision set not null;

alter table algorithm_versions add constraint algorithm_versions_family_revision_key unique (family, revision);

create index on algorithm_versions (family);
